---
title: Working in teams
---

:callout :small, "share!", "Lets hear from some students who have worked on teams or led teams"

* In all my courses I ask students to work on projects in teams. 
* I have seen them succeed and have seen them struggle. 
* These notes are based on this hard won experience with student run teams.
* What kinds of ideas or approaches have you used (or been used on you) that you think are good?
* Lets hear some horror stories?
