---
title: "(I) Answer \"About Me\" questionnaire"
---
### What is this?

A quick questionnaire to learn more about you.

### Why am I doing this?

We use this and other information to create the teams

### Please do this

Simply respond to [the questions in this questionnaire](https://forms.gle/1QuRkE9U7fS3sZkBA)

### To Receive a "Meets" or better

1. Follow the instructions
1. Write a good faith response





