---
title: Product Vision
desc: Write a summary of your product vision
---
* **Product Vision**: Your current vision of the product. Make it descriptive, not sales-y. Remember the reader is not inside your head they will need to have it explained.
* **Problems that it solves**: Continue your explanation by explicitly stating the list of 1 or 2 or 3 real world user problems that it solves. Make it pass the common sense tests. These should not be tiny silly problems but should be recognizable by the target users. Distinguish between problems you solve and pains you remove.
* **Who is/are the customer/s**: Describe groups of users or customers in a way that keeps in mind how you might reach them. If your customers are "Higher Ed Students who are having trouble finishing their homework on time". How would you find them to talk to them and dig deeper? Also remember that your vision might include two disjoint sets of users or customers.
* **Money** How might this business make money or be self-sustaining? Where do the funds come from? You know how you feel about having to pay for an app or a subscription, right? The pain that your business solves should be significant, not trivial.

:team_deliverable "Your 1 page product vision, as a pdf"