---
title: Watch Sharktank!
desc: What a fun homework!
---
## 2 Shark Tank!

Watch one episode of **Shark Tank** a TV show about fake venture capitalists. As you watch it, think of these questions and give brief comments.

* Which episode did you watch?

* What did you see that you had never seen before?

* How did it make you feel?

* What could you learn from this?

* How real or fake do you think this was?
