---
title: Intellectual Property Reading
desc: Practice starting to think about IP issues
---
### Purpose 
There are several ways to make sure that your work is not stolen or copied. They each have certain benefits and costs. As an entrepreneur it's important to understand each of them. This small homework is mostly reading and thinking. But it's important to spend some time engaging with them.

### Please do this

Basic definitions: Please read these Wikipedia articles: [What are Copyrights?](http://en.wikipedia.org/wiki/Copyright), [What are Trade Secrets?](http://en.wikipedia.org/wiki/Trade_secret), [What are Patents?](http://en.wikipedia.org/wiki/Patents).  We will talk about this in class. To practice. here are some questions:

* In the show [Silicon Valley](http://www.hbo.com/silicon-valley), the team from [Pied Piper](http://www.piedpiper.com) has perfected a new compression algorithm which works far more effectively than what came before. Should they employ Trade Secrets, Patents, Copyrights to protect their invention? Explain your reasoning. If you think they would use a combination, then explain how and why.
* Can you envision a scenario where you use both Patent and Trade Secret protection to protect the same product? Explain your response.
    