---
title: "Read Lean Startup Chapters 4 and 5"
desc: The Lean Startup is the main textbook for this course
---

### Read The Lean Startup Chapter 4 and 5. Please consider the following warmup questions

### Think and answer the following warmup questions from Chapter 4 and 5 

* Explain what a concierge MVP is and how it is used
* What does Eric Ries mean by "getting out of the building"? What message is he trying to get across? What mistake is he trying to teach you to avoid?

