---
title: "(T) Team Brainstorm: A few more original ideas"
desc: Continue with the techniques to come up with more new ideas
cat: activity
---
### What is this?
* Brainstorm with a group to refine, adopt, adapt your business ideas
* Come up with your favite three

### Purpose

* Develop the product or business idea which will become your term project
* Develop a sense of belonging and team
* Learn how to interact, resolve disagreement and reaching consensus

### Please do this:

* **Meet**: Twice in the week, for at least 1 hour each with all team members participating. Brainstorm product ideas. Use any and all resources. Including: any of the ideas that teammates have come up with, our list of :topic_link :product_ideas. Also look at :topic_link :product_inspirations and any thing you can find in google or elsewhere. Ask ChatGPT for idaas!
* **Problems**: Look for real problems or pains that exist that your product could address, what is the "job" that the product is doing for the customer, and who that customer might be. Consider whether your team has any domain experties.
* **Submit as a team**:  Converge on your favorite three product ideas as a team. Write them up, in priority order, with a short description of each. Include a product name, a tweet-length description, a longer description, a summary of the target customer, what the pain is that your product will solve.
* **Format**: Submit as a single PDF. One teammate submits it and it will automatically apply to all the teammates.
* **Authorship**: Indicate who the AL was, and indicate each KC (team mate who contributed to this deliverable) and how they contributed to the deliverable. For example, what section they wrote, or what work they did

### To Meet Expectations

1. Follow the instructions carefully
1. Each product should demonstrate real thinking, a real pain point, and a degree of plausibility.
