---
title: Team Alignment
desc: Work with your team to make sure everyone's on the same page.
cat: activity
---
## Team Alignment
We're getting close to having to settle on a product for the team - there's one more week to get to your stage 1 report! You still have time to tweak it or pivot from it, but it's time to start nailing things down! 

Meet for at least 2 hours, face to face with your team and come up with your team's product vision with the following elements. Notice that for this exercise it is necessary to discuss each point in the team meeting and articulate your answer in a fairly precise way that you all can accept. I realize that they are so far not tested; you will be able to improve and amend them in the coming days and weeks. The important thing at this point is that all team members engage and understand and agree with the vision as of now and can get excited about really working out the details!

