---
title: F35 Software bug
---
Read [The F35s terrible bug list](http://www.defenseone.com/technology/2016/02/f-35s-terrifying-bug-list/125638/?oref=DefenseOneTCO)

It's an interesting view into the real world impact that bugs have. Also that Fighter jets are really computers with wings on them! Also read [There's more to Ruby Debugging than puts](https://engineering.shopify.com/17489080-theres-more-to-ruby-debugging-than-puts?utm_medium=email&utm_source=rubyweekly). Lots of very practical tips and ideas about debugging, as well as some really useful Ruby tricks.

:deliverable None