---
title: "Lean Startup Chapter 9: Batch"
desc: Why the Lean Startup is called "Lean"
---
:slide_bigtitle Key Takeaway from Chapter 9 - Batch

* **BIG IDEA**: Small batches, short iterations, Lean

* Originally came from Toyota (Supply chain management, Just in time manufacturing)
* Led to the standard software engineering pratice "Agile Software Development"
* Compare to waterfall software engineering process
* Gradually has moved into all kinds of other areas (see Lean Startup!)
