---
title: Heroku Deploy setup
---
:slide_bigtitle Directly pushing from Github

Heroku has built-in function for deploying changes directly from Github to your Heroku app. This tutorial will go through how to set it up.

## Step 1: Connect Github repo to Heroku

*Note: Skip this step if you already connected the Github repo to Heroku.*

:image :connect_github

Click "Connect to GitHub" using an account that either owns the project repo, or has contributor access to the repo.

## Step 2: Choose the correct repo

*Note: Skip this step if you already connected the Github repo to Heroku.*

:image :connect_repo

Click "Connect" to the project repo. E.g. `hojulian/ruby-getting-started`.

## Step 3: Enable Automatic deploys

To tell Heroku to deploy on new code changes, enable "Automatic Deploys".

:image :enable_auto_deploy

Choose the branch where the newest changes are located (this is usually `main`). And click "Enable Automatic Deploys".

This will enable automatic deployment on the Heroku side.

## Step 4: Deploying for the first time

*Note: Skip this step if your project is already up and running on Heroku*

Since your app is deployed yet, you will need to manually deploy it for the first time.

:image :deploy_first_time

Click "Deploy Branch" and Heroku will pull the latest copy of your project and deploy it!

On success, you will see a green tick next to "Deploy to Heroku". If it failed, check the Build logs for any errors.
