---
title: David Coletta
---

:h3 David Coletta

:image :200, :david_coletta_head

Is the CTO of High Hopes LLC. He is a software engineer and architect, who worked on many projects and products over the years. Before High Hopes he was in R&D at Adobe Products.

<a class="embedly-card" data-card-align="left" href="https://www.linkedin.com/in/davidcoletta/">
    David Coletta| LinkedIn!
</a> 
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>