---
title: (P) Term Project proposals
desc: Lets come up with some great ideas!
---

* This is a team project
* It can be done with a physical robot, with simulation and in other ways that I can introduce
* We will be brainstorming in class for ideas
* This assignment is for you to research and writeup two different project ideas.
* The writeup should be 1-2 paragraphs, and include a name and your name plus proposed team mate(s) if any

:deliverable Your Term project proposal as pdf

