---
title: Why Can't Programmers Program?
---
:h3 Purpose 

A quick read to remind you of the importance of just coding. It will help you think about where you want to be by the time you graduate. And there are no shortcuts. In addition to all the theory and abstract concepts, you need to get into the arena and write code. Like any skill, you have to practice it a lot, but it is well within your capabilities. How do I know? Well, you got into Brandeis and that says a lot!

:h3 Please do this

**Read [Why Cant Programmers Program?](http://blog.codinghorror.com/why-cant-programmers-program/)