---
title: "Ideas2: Team Brainstorm: A few more original ideas"
desc: Continue with the techniques to come up with more new ideas
cat: Ideas
---
### What is this?
* Brainstorm with a group to refine, adopt, adapt your business ideas
* Come up with your favorite three.

### Skills
* Ideas: Generating startup ideas

### Purpose

* Develop the product or business idea which will become your term project
* Practice brainstorming with peers, sharing and building on each others' ideas
* Learn how to interact, resolve disagreement and reaching consensus

### Please do this:

* **Meet**: Twice in the week, for at least 1 hour each with a group of 4 students. Brainstorm product ideas. Use any and all resources. Including: any of the ideas that teammates have come up with, our list of :topic_link :product_ideas. Also look at :topic_link :product_inspirations and any thing you can find in google or elsewhere. Ask ChatGPT for ideas!
* **Problems**: Look for real problems or pains that exist that your product could address, what is the "job" that the product is doing for the customer, and who that customer might be. Consider whether your team has any domain expertise.
* **Submit individually**: Converge on your favorite four product ideas as a team. Each student on the team writes up one of them. Include a short description of each. Include a product name, a tweet-length description, a longer description, a summary of the target customer, what the pain is that your product will solve.

### To Meet Expectations

1. Follow the instructions carefully
1. Each product should demonstrate real thinking, a real pain point, and a degree of plausibility.
