---
title: "Hyp: Generate three hypotheses"
desc: An exercise to learn about hypotheses
cat: Hyp
---
### Purpose
Testing an MVP works best if you know what you are looking for. This is why the Lean Startup approach reqires that you think through and come up with one or more hypotheses. THis homwework gives you a chance to practice doing this. 

### Skills
* Hypotheses; How to Formulate and test hypotheses
  
## Read these articles


## Do this

