---
title: Cosi102a Final Deliverables
---
## Final deliverables

1. Your Stage 3 Report is also the final report for your term project. Therefore I've renamed it accordingly. Here are the details of the :topic_link :hw_102_proj_stage3

1. In addition to the Final report you will also be responsible as a team to create a video presentation of your project. Here are the details: :topic_link :final_video_presentation. If you want feedback ahead of time (optional) you can touch base with Pito no later than December 4 to look over a draft, a script, a storyboard, or whatever you have so far so I can give you some feedback and tips. 

1. This is a few specific text and image files that allow me to easily put your project on the Brandeis Projects web site: :topic_link :brandeisprojects_listing