---
title: Cosi102a Final Deliverables
---
## Final deliverables

1. Your Stage 3 Report is also the final report for your term project. Therefore I've renamed it accordingly. Here are the details of the :topic_link :hw_102r_proj_stage3

1. In addition to the Final report you will also be responsible as a team to present your project. The logistical details will be announced. Look at :topic_link :cosi102a_final_presentation for hints and details.

1. This is a few specific text and image files that allow me to easily put your project on the Brandeis Projects web site: :topic_link :brandeisprojects_listing