---
title: AI Tools Policy for Cosi119a
date: 15-jun-2024
author: Pito Salas
---
### Artificial Intelligence Tools

:callout :small, "note: ", "This includes any AI tools but especially so called Large Language Model Chat tools like ChatGpt and others."

I believe that these tools have become essential part of the toolkit for any Robotics Engineer (and any Developer, Software Engineer or Computer Scientist) In fact I will go as far as to say that without developing skills using the tools you are working with one hand tied behind your back and putting yourself at an unacceptable competitive disadvantage.

