---
title: AI Tools Policy for Cosi102a
date: 15-jun-2024
author: Pito Salas
---
### Artificial Intelligence Tools

:callout :small, "note:", "AI Tools include any AI tools but especially so called Large Language Model Chat tools like ChatGpt and others."

"AI Tools" broadly speaking are useful tools in our toolkits, like google and youtube and grammarly. But remember that LLMs are trained on other peope's text which in a way is the very essence of plagiarism or intellectual theft. In this class you are not prohibited from using an "AI Tool" for research, brainstorming, fact checking, learning about tools or how to use them. 

But, copying any text, diagram, table, or other content from the web, AI tools, google and all the rest is strictly prohibted and would be considered a serious breach of academic freedom. 

**If you are not sure, it is always better to ask a TA or the professor if you’re not certain!**
