---
title: Career Advice Reading
desc: In preparation for our real world discussion, read some seminal articles
---
### Purpose
As at other times, I am asking you to read these article that articulate some ideas and principles which I believe are very important.

### Do this
Please read:

* [The No.1 Predictor of Career Success](https://medium.com/accelerated-intelligence/the-number-one-predictor-of-career-success-according-to-network-science-be7fcc8e9558)
* [The Most Important piece of advice for folks starting their careers](https://medium.com/@jason/the-most-important-piece-of-advice-for-folks-starting-their-careers-9265d689655d)
* [The One Skill that beats talent every time](https://medium.com/on-breaking-the-mold/the-one-skill-that-beats-talent-every-time-cf269cf23c55)

