---
title: Management and Leadership
desc: Learn by reading some key articles
---
### The purpose of this assignment
My goal is to share with you different perspectives on leadership and management. I have selected some articles that I have found useful and meaningful in learning about leadership and management

### Do this
Please read these articles: 

* [14 Ways to become a better Technical Manager and Leader](https://medium.com/@yagiz/14-ways-to-become-a-better-technical-manager-leader-7b57324c2a6d) (5 minutes)
( [How to make the most of a tiny tech team](https://www.forbes.com/sites/forbestechcouncil/2016/05/06/how-to-make-the-most-of-a-tiny-tech-team/#248d7c6a6c0e) (5 minutes)
* [Later](https://www.newyorker.com/magazine/2010/10/11/later) (10 minutes)
* [The Lean Startup is an unproductive legend](https://qz.com/work/1349238/the-lean-startup-is-an-unproductive-legend/) (5 minutes)
* [Chaos Monkeys Interview](https://www.youtube.com/watch?v=W3hG8aZ88Jc) (20 minutes)

