---
title: Participation in in-person classes
---
Attendance is required for in-person classes such as this one. We monitor it and regular unexcused absences will definitely affect your grade.

However if you have a reason why you cannot participate in person, you are welcome to ask to be excused. We will listen to all reasonable requests.

Please email your lead TA to ask for an excused absence.

