---
title: Grading Cheatsheet
desc: Top level summary of Grading
slides: true
---
:slide_bigtitle Grading

* Grading will be a little different
* All of your work will be "graded" as "Meets expectations" or "does Not meet expectations"
* So, no partial credit!
* All assignments include a detailed section: "To Receive a Meets Expectations" (or words to that effect)

:slide_title Types of Assignments

* Individual
* Reflection
* Team

:topic_include :cosi102_grade_bundles
